# You are given two strings s and t.
# String t is generated by random shuffling string s and then add one more letter at a random position.
# Return the letter that was added to t.


class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        s = list(s)
        s.sort()
        t = list(t)
        t.sort()
        for j in range(len(s)):
            if s[j] != t[j]:
                return t[j]
        return t[-1]
